//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.13.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "ajustesNoticias"
	/// <summary>Ajustes Noticias</summary>
	public partial interface IAjustesNoticias : IPublishedElement
	{
		/// <summary>Autor</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		string Autor { get; }

		/// <summary>Categorías</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		global::System.Collections.Generic.IEnumerable<string> Categorias { get; }

		/// <summary>Eslogan</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		string Eslogan { get; }

		/// <summary>Fecha De Publicación</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		global::System.DateTime FechaDePublicacion { get; }

		/// <summary>Foto Principal</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		global::Umbraco.Core.Models.PublishedContent.IPublishedContent FotoPrincipal { get; }

		/// <summary>Miniatura</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		global::Umbraco.Core.Models.PublishedContent.IPublishedContent Miniatura { get; }

		/// <summary>Texto</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		global::Newtonsoft.Json.Linq.JToken Texto { get; }
	}

	/// <summary>Ajustes Noticias</summary>
	[PublishedModel("ajustesNoticias")]
	public partial class AjustesNoticias : PublishedElementModel, IAjustesNoticias
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public new const string ModelTypeAlias = "ajustesNoticias";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AjustesNoticias, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public AjustesNoticias(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Autor
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		[ImplementPropertyType("autor")]
		public virtual string Autor => GetAutor(this);

		/// <summary>Static getter for Autor</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public static string GetAutor(IAjustesNoticias that) => that.Value<string>("autor");

		///<summary>
		/// Categorías
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		[ImplementPropertyType("categorias")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Categorias => GetCategorias(this);

		/// <summary>Static getter for Categorías</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public static global::System.Collections.Generic.IEnumerable<string> GetCategorias(IAjustesNoticias that) => that.Value<global::System.Collections.Generic.IEnumerable<string>>("categorias");

		///<summary>
		/// Eslogan
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		[ImplementPropertyType("eslogan")]
		public virtual string Eslogan => GetEslogan(this);

		/// <summary>Static getter for Eslogan</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public static string GetEslogan(IAjustesNoticias that) => that.Value<string>("eslogan");

		///<summary>
		/// Fecha De Publicación
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		[ImplementPropertyType("fechaDePublicacion")]
		public virtual global::System.DateTime FechaDePublicacion => GetFechaDePublicacion(this);

		/// <summary>Static getter for Fecha De Publicación</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public static global::System.DateTime GetFechaDePublicacion(IAjustesNoticias that) => that.Value<global::System.DateTime>("fechaDePublicacion");

		///<summary>
		/// Foto Principal
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		[ImplementPropertyType("fotoPrincipal")]
		public virtual global::Umbraco.Core.Models.PublishedContent.IPublishedContent FotoPrincipal => GetFotoPrincipal(this);

		/// <summary>Static getter for Foto Principal</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public static global::Umbraco.Core.Models.PublishedContent.IPublishedContent GetFotoPrincipal(IAjustesNoticias that) => that.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("fotoPrincipal");

		///<summary>
		/// Miniatura
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		[ImplementPropertyType("miniatura")]
		public virtual global::Umbraco.Core.Models.PublishedContent.IPublishedContent Miniatura => GetMiniatura(this);

		/// <summary>Static getter for Miniatura</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public static global::Umbraco.Core.Models.PublishedContent.IPublishedContent GetMiniatura(IAjustesNoticias that) => that.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("miniatura");

		///<summary>
		/// Texto
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		[ImplementPropertyType("texto")]
		public virtual global::Newtonsoft.Json.Linq.JToken Texto => GetTexto(this);

		/// <summary>Static getter for Texto</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public static global::Newtonsoft.Json.Linq.JToken GetTexto(IAjustesNoticias that) => that.Value<global::Newtonsoft.Json.Linq.JToken>("texto");
	}
}
